language: node_js
node_js:
  - "9.11.1"

cache:
  npm: false

dist: focal
sudo: true

branches:
  only:
      - master
      - develop
      - panosc-demo
addons:
  chrome: stable

before_script:
  - npm install -g @angular/cli@7.2.0
  - cp src/environments/environment.docker.ts.example src/environments/environment.ts

script:
  - ng lint
  - ng test --watch=false
